name: LightHouse CI

on:
  pull_request:
    branches:
      - main
      - release

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install packages
        run: yarn install && yarn global add @lhci/cli@0.13.x && yarn add @actions/core

      - name: Set .env
        run: echo "${{ vars.DEVELOPMENT_ENV }}" > .env.local

      - name: Build
        run: yarn build

      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Get Score Comments
        id: get-score-comments
        uses: ./.github/actions/get-score-comments

      - name: Comment On PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.get-score-comments.outputs.comments }}
